# Pre-commit hooks configuration for CarIActerology
# Install with: pre-commit install

repos:
  # Ruff - Fast Python linter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.9
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        name: ruff-linting
      - id: ruff-format
        name: ruff-formatting

  # Black - Python code formatter
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        name: black-formatting
        language_version: python3
        args: [--line-length=88]

  # mypy - Static type checker
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        name: mypy-type-checking
        additional_dependencies: [
          types-requests,
          types-python-dateutil,
          streamlit,
          plotly,
          pandas-stubs,
          types-Pillow
        ]
        args: [--ignore-missing-imports, --no-strict-optional]

  # Standard pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        name: trim-whitespace
      - id: end-of-file-fixer
        name: fix-end-of-files
      - id: check-merge-conflict
        name: check-merge-conflicts
      - id: check-yaml
        name: check-yaml-syntax
      - id: check-json
        name: check-json-syntax
      - id: check-toml
        name: check-toml-syntax
      - id: check-added-large-files
        args: [--maxkb=1000]
        name: check-large-files
      - id: check-case-conflict
        name: check-filename-case
      - id: mixed-line-ending
        name: fix-line-endings

  # Security scanning
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.6
    hooks:
      - id: bandit
        args: [-c, .bandit]
        name: security-scan
        exclude: ^tests/

  # Documentation
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        name: docstring-style
        args: [--convention=google]
        exclude: ^(tests/|migrations/)

  # Import sorting
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: sort-imports
        args: [--profile, black, --multi-line=3]

  # Jupyter notebooks
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.7.1
    hooks:
      - id: nbqa-black
        name: black-jupyter
      - id: nbqa-ruff
        name: ruff-jupyter

# Configuration for specific file types
files: ^(app\.py|pages/.*\.py|modules/.*\.py|data/.*\.py|tests/.*\.py)$
exclude: |
  (?x)^(
    venv/.*|
    \.venv/.*|
    mem0_doc/.*|
    openai_agents_sdk_examples_and_doc/.*|
    \.git/.*|
    __pycache__/.*
  )$

# CI configuration
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: []
  submodules: false