[theme]
# Primary color for therapeutic branding
primaryColor = "#667eea"

# Background color
backgroundColor = "#ffffff"

# Secondary background color (for sidebar, etc.)
secondaryBackgroundColor = "#f8f9fc"

# Text color
textColor = "#262730"

# Font family
font = "sans serif"

[server]
# Server configuration for better performance
maxUploadSize = 200
maxMessageSize = 200
enableCORS = false
enableXsrfProtection = true
enableWebsocketCompression = true

[browser]
# Browser configuration
gatherUsageStats = false
serverAddress = "0.0.0.0"

[client]
# Client configuration
toolbarMode = "viewer"
showErrorDetails = false